<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class AssetHolder
{
    /**
     * $assets
     * 
     * @var array<string, float> $assets
     */
	#[\JMS\Serializer\Annotation\SerializedName('assets')]
    #[\JMS\Serializer\Annotation\Type('array<string, float>')]
    public array $assets;
    
	public function __construct()
	{
		$this->assets = [];
	}
}
