<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


enum PaymentsAccountTypeEnum: string
{
    case TARGET = 'TARGET';
    case SOURCE = 'SOURCE';
}
