<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class PaymentsAccount
{
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('provider')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\stack\Models\Shared\ConnectorEnum>')]
    public ConnectorEnum $provider;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $reference;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\stack\Models\Shared\PaymentsAccountTypeEnum>')]
    public PaymentsAccountTypeEnum $type;
    
	public function __construct()
	{
		$this->createdAt = new \DateTime();
		$this->id = "";
		$this->provider = \formance\stack\Models\Shared\ConnectorEnum::STRIPE;
		$this->reference = "";
		$this->type = \formance\stack\Models\Shared\PaymentsAccountTypeEnum::TARGET;
	}
}
