// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConfigsResponseCursor struct {
	Data    []interface{} `json:"data"`
	HasMore bool          `json:"hasMore"`
}

// ConfigsResponse - OK
type ConfigsResponse struct {
	Cursor ConfigsResponseCursor `json:"cursor"`
}
