<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack;

class Scopes 
{

	// SDK private variables namespaced with _ to avoid conflicts with API models
	private \GuzzleHttp\ClientInterface $_defaultClient;
	private \GuzzleHttp\ClientInterface $_securityClient;
	private string $_serverUrl;
	private string $_language;
	private string $_sdkVersion;
	private string $_genVersion;	

	/**
	 * @param \GuzzleHttp\ClientInterface $defaultClient
	 * @param \GuzzleHttp\ClientInterface $securityClient
	 * @param string $serverUrl
	 * @param string $language
	 * @param string $sdkVersion
	 * @param string $genVersion
	 */
	public function __construct(\GuzzleHttp\ClientInterface $defaultClient, \GuzzleHttp\ClientInterface $securityClient, string $serverUrl, string $language, string $sdkVersion, string $genVersion)
	{
		$this->_defaultClient = $defaultClient;
		$this->_securityClient = $securityClient;
		$this->_serverUrl = $serverUrl;
		$this->_language = $language;
		$this->_sdkVersion = $sdkVersion;
		$this->_genVersion = $genVersion;
	}
	
    /**
     * Add a transient scope to a scope
     * 
     * Add a transient scope to a scope
     * 
     * @param \formance\stack\Models\Operations\AddTransientScopeRequest $request
     * @return \formance\stack\Models\Operations\AddTransientScopeResponse
     */
	public function addTransientScope(
        \formance\stack\Models\Operations\AddTransientScopeRequest $request,
    ): \formance\stack\Models\Operations\AddTransientScopeResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes/{scopeId}/transient/{transientScopeId}', \formance\stack\Models\Operations\AddTransientScopeRequest::class, $request);
        
        $options = ['http_errors' => false];
        
        $httpResponse = $this->_securityClient->request('PUT', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\AddTransientScopeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 204) {
        }

        return $response;
    }
	
    /**
     * Create scope
     * 
     * Create scope
     * 
     * @param \formance\stack\Models\Shared\CreateScopeRequest $request
     * @return \formance\stack\Models\Operations\CreateScopeResponse
     */
	public function createScope(
        \formance\stack\Models\Shared\CreateScopeRequest $request,
    ): \formance\stack\Models\Operations\CreateScopeResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "json");
        $options = array_merge_recursive($options, $body);
        
        $httpResponse = $this->_securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\CreateScopeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 201) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->createScopeResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'formance\stack\Models\Shared\CreateScopeResponse', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Delete scope
     * 
     * Delete scope
     * 
     * @param \formance\stack\Models\Operations\DeleteScopeRequest $request
     * @return \formance\stack\Models\Operations\DeleteScopeResponse
     */
	public function deleteScope(
        \formance\stack\Models\Operations\DeleteScopeRequest $request,
    ): \formance\stack\Models\Operations\DeleteScopeResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes/{scopeId}', \formance\stack\Models\Operations\DeleteScopeRequest::class, $request);
        
        $options = ['http_errors' => false];
        
        $httpResponse = $this->_securityClient->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\DeleteScopeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 204) {
        }

        return $response;
    }
	
    /**
     * Delete a transient scope from a scope
     * 
     * Delete a transient scope from a scope
     * 
     * @param \formance\stack\Models\Operations\DeleteTransientScopeRequest $request
     * @return \formance\stack\Models\Operations\DeleteTransientScopeResponse
     */
	public function deleteTransientScope(
        \formance\stack\Models\Operations\DeleteTransientScopeRequest $request,
    ): \formance\stack\Models\Operations\DeleteTransientScopeResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes/{scopeId}/transient/{transientScopeId}', \formance\stack\Models\Operations\DeleteTransientScopeRequest::class, $request);
        
        $options = ['http_errors' => false];
        
        $httpResponse = $this->_securityClient->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\DeleteTransientScopeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 204) {
        }

        return $response;
    }
	
    /**
     * List scopes
     * 
     * List Scopes
     * 
     * @return \formance\stack\Models\Operations\ListScopesResponse
     */
	public function listScopes(
    ): \formance\stack\Models\Operations\ListScopesResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes');
        
        $options = ['http_errors' => false];
        
        $httpResponse = $this->_securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\ListScopesResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->listScopesResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'formance\stack\Models\Shared\ListScopesResponse', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Read scope
     * 
     * Read scope
     * 
     * @param \formance\stack\Models\Operations\ReadScopeRequest $request
     * @return \formance\stack\Models\Operations\ReadScopeResponse
     */
	public function readScope(
        \formance\stack\Models\Operations\ReadScopeRequest $request,
    ): \formance\stack\Models\Operations\ReadScopeResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes/{scopeId}', \formance\stack\Models\Operations\ReadScopeRequest::class, $request);
        
        $options = ['http_errors' => false];
        
        $httpResponse = $this->_securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\ReadScopeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->readScopeResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'formance\stack\Models\Shared\ReadScopeResponse', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Update scope
     * 
     * Update scope
     * 
     * @param \formance\stack\Models\Operations\UpdateScopeRequest $request
     * @return \formance\stack\Models\Operations\UpdateScopeResponse
     */
	public function updateScope(
        \formance\stack\Models\Operations\UpdateScopeRequest $request,
    ): \formance\stack\Models\Operations\UpdateScopeResponse
    {
        $baseUrl = $this->_serverUrl;
        $url = Utils\Utils::generateUrl($baseUrl, '/api/auth/scopes/{scopeId}', \formance\stack\Models\Operations\UpdateScopeRequest::class, $request);
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "updateScopeRequest", "json");
        $options = array_merge_recursive($options, $body);
        
        $httpResponse = $this->_securityClient->request('PUT', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \formance\stack\Models\Operations\UpdateScopeResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->updateScopeResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'formance\stack\Models\Shared\UpdateScopeResponse', 'json');
            }
        }

        return $response;
    }
}