linters:
  enable:
    - gofmt
    - gci
    - goimports

  presets:
    - bugs
    - comment
    - error
    - format
    - import
    - unused

  disable:
    - contextcheck
    - godox
    - varcheck
    - scopelint
    - deadcode
    - structcheck
    - rowserrcheck
    - sqlclosecheck
    - wrapcheck
    - exhaustive
    - buildir

run:
  timeout: 5m
