/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import java.net.http.HttpResponse;

public class GetLedgerInfoResponse {
    public String contentType;
    public GetLedgerInfoResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Error
     */
    public com.formance.formance_sdk.models.shared.ErrorResponse errorResponse;
    public GetLedgerInfoResponse withErrorResponse(com.formance.formance_sdk.models.shared.ErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    /**
     * OK
     */
    public Object ledgerInfoResponse;
    public GetLedgerInfoResponse withLedgerInfoResponse(Object ledgerInfoResponse) {
        this.ledgerInfoResponse = ledgerInfoResponse;
        return this;
    }
    
    public Integer statusCode;
    public GetLedgerInfoResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public HttpResponse<byte[]> rawResponse;
    public GetLedgerInfoResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
