/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import java.net.http.HttpResponse;

public class GetManyConfigsResponse {
    /**
     * OK
     */
    public com.formance.formance_sdk.models.shared.ConfigsResponse configsResponse;
    public GetManyConfigsResponse withConfigsResponse(com.formance.formance_sdk.models.shared.ConfigsResponse configsResponse) {
        this.configsResponse = configsResponse;
        return this;
    }
    
    public String contentType;
    public GetManyConfigsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    public Integer statusCode;
    public GetManyConfigsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public HttpResponse<byte[]> rawResponse;
    public GetManyConfigsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
