/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import java.net.http.HttpResponse;

public class ListInstancesResponse {
    public String contentType;
    public ListInstancesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * General error
     */
    public com.formance.formance_sdk.models.shared.Error error;
    public ListInstancesResponse withError(com.formance.formance_sdk.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * List of workflow instances
     */
    public Object listRunsResponse;
    public ListInstancesResponse withListRunsResponse(Object listRunsResponse) {
        this.listRunsResponse = listRunsResponse;
        return this;
    }
    
    public Integer statusCode;
    public ListInstancesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public HttpResponse<byte[]> rawResponse;
    public ListInstancesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
