/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import java.net.http.HttpResponse;

public class ListConnectorTasksResponse {
    public String contentType;
    public ListConnectorTasksResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    public Integer statusCode;
    public ListConnectorTasksResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public HttpResponse<byte[]> rawResponse;
    public ListConnectorTasksResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    public com.formance.formance_sdk.models.shared.TasksCursor tasksCursor;
    public ListConnectorTasksResponse withTasksCursor(com.formance.formance_sdk.models.shared.TasksCursor tasksCursor) {
        this.tasksCursor = tasksCursor;
        return this;
    }
    
}
