/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.SpeakeasyMetadata;

public class ReadScopeRequest {
    /**
     * Scope ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=scopeId")public String scopeId;
    public ReadScopeRequest withScopeId(String scopeId) {
        this.scopeId = scopeId;
        return this;
    }
    
}
