/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.SpeakeasyMetadata;

public class ReadUserRequest {
    /**
     * User ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")public String userId;
    public ReadUserRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
}
