/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import java.net.http.HttpResponse;

public class ReadStatsResponse {
    public String contentType;
    public ReadStatsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Error
     */
    public com.formance.formance_sdk.models.shared.ErrorResponse errorResponse;
    public ReadStatsResponse withErrorResponse(com.formance.formance_sdk.models.shared.ErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    /**
     * OK
     */
    public com.formance.formance_sdk.models.shared.StatsResponse statsResponse;
    public ReadStatsResponse withStatsResponse(com.formance.formance_sdk.models.shared.StatsResponse statsResponse) {
        this.statsResponse = statsResponse;
        return this;
    }
    
    public Integer statusCode;
    public ReadStatsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public HttpResponse<byte[]> rawResponse;
    public ReadStatsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
