/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.SpeakeasyMetadata;

public class ReadClientRequest {
    /**
     * Client ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=clientId")public String clientId;
    public ReadClientRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    
}
