/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import java.net.http.HttpResponse;

public class ReadConnectorConfigResponse {
    /**
     * OK
     */
    public com.formance.formance_sdk.models.shared.ConnectorConfigResponse connectorConfigResponse;
    public ReadConnectorConfigResponse withConnectorConfigResponse(com.formance.formance_sdk.models.shared.ConnectorConfigResponse connectorConfigResponse) {
        this.connectorConfigResponse = connectorConfigResponse;
        return this;
    }
    
    public String contentType;
    public ReadConnectorConfigResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    public Integer statusCode;
    public ReadConnectorConfigResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    public HttpResponse<byte[]> rawResponse;
    public ReadConnectorConfigResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
