/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateWalletRequestBody {
    /**
     * Custom metadata to attach to this wallet.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")public java.util.Map<String, Object> metadata;
    public UpdateWalletRequestBody withMetadata(java.util.Map<String, Object> metadata) {
        this.metadata = metadata;
        return this;
    }
    
}
