VERSION 0.7

sources:
    FROM ../..+base-build-image
    DO ../..+GO_PKG_CACHE
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=libs/go-libs
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=sdks/go
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=components/wallets
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=sdks/go
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=libs/go-libs
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=components/wallets

    WORKDIR /src/components/wallets

build:
    FROM +sources
    DO ../..+STD_BUILD --COMPONENT=wallets

build-image:
    FROM ../..+base-final-image
    COPY (+build/wallets) /bin/wallets
    ENTRYPOINT ["/bin/wallets"]

    DO ../..+SAVE_IMAGE --COMPONENT=wallets

tests:
    FROM +sources
    DO ../..+TESTS

lint:
    FROM +sources
    DO ../..+LINT
