VERSION 0.7

sources:
    FROM ../..+base-build-image
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=libs/go-libs
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=components/search
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=libs/go-libs
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=components/search

    WORKDIR /src/components/search

build:
    FROM +sources
    DO ../..+STD_BUILD --COMPONENT=search

build-image:
    FROM ../..+base-final-image
    COPY (+build/search) /bin/search
    ENTRYPOINT ["/bin/search"]

    DO ../..+SAVE_IMAGE --COMPONENT=search

    WORKDIR /src/components/search

opensearch:
    FROM opensearchproject/opensearch:1.2.3

tests:
    FROM +sources
    WITH DOCKER --allow-privileged \
        --load opensearchproject/opensearch:1.2.3=+opensearch
        RUN go test -v ./...
    END

lint:
    FROM +sources
    DO ../..+LINT
