VERSION 0.7

sources:
    FROM ../..+base-build-image
    DO ../..+LOAD_SOURCES --LOCATION=libs/go-libs
    DO ../..+DOWNLOAD_DEPENDENCIES --LOCATION=components/auth
    DO ../..+LOAD_SOURCES --LOCATION=components/auth

    WORKDIR /src/components/auth

build-image:
    FROM ../..+base-final-image
    COPY (../..+build/auth --COMPONENT=auth) /bin/auth
    ENTRYPOINT ["/bin/auth"]

    DO ../..+SAVE_IMAGE --COMPONENT=auth

tests:
    FROM +sources
    WITH DOCKER --allow-privileged \
        --load postgres:15-alpine=+postgres
        DO ../..+GO_STD_TEST_COMMAND
    END
