VERSION 0.7

sources:
    FROM ../..+base-build-image
    DO ../..+GO_PKG_CACHE
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=libs/go-libs
    DO ../..+DOWNLOAD_DEPENDENCIES --DEPENDENCY_PATH=components/auth
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=libs/go-libs
    DO ../..+LOAD_SOURCES --DEPENDENCY_PATH=components/auth

    WORKDIR /src/components/auth

build:
    FROM +sources
    DO ../..+STD_BUILD --COMPONENT=auth

build-image:
    FROM ../..+base-final-image
    COPY (+build/auth) /bin/auth
    ENTRYPOINT ["/bin/auth"]

    DO ../..+SAVE_IMAGE --COMPONENT=auth

tests:
    FROM +sources
    DO ../..+TESTS --CGO_ENABLED=1

lint:
    FROM +sources
    DO ../..+LINT
