/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AttemptResponse - OK
 */
public class AttemptResponse {
    @JsonProperty("data")public Object data;
    public AttemptResponse withData(Object data) {
        this.data = data;
        return this;
    }
    
}
