/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ConfigResponse - Config created successfully.
 */
public class ConfigResponse {
    @JsonProperty("data")public Object data;
    public ConfigResponse withData(Object data) {
        this.data = data;
        return this;
    }
    
}
