/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Hold {
    @JsonProperty("description")public String description;
    public Hold withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("destination")public Object destination;
    public Hold withDestination(Object destination) {
        this.destination = destination;
        return this;
    }
    
    /**
     * The unique ID of the hold.
     */
    @JsonProperty("id")public String id;
    public Hold withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * Metadata associated with the hold.
     */
    @JsonProperty("metadata")public java.util.Map<String, Object> metadata;
    public Hold withMetadata(java.util.Map<String, Object> metadata) {
        this.metadata = metadata;
        return this;
    }
    
    /**
     * The ID of the wallet the hold is associated with.
     */
    @JsonProperty("walletID")public String walletID;
    public Hold withWalletID(String walletID) {
        this.walletID = walletID;
        return this;
    }
    
}
