/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WalletsErrorResponse - Error
 */
public class WalletsErrorResponse {
    @JsonProperty("errorCode")public WalletsErrorResponseErrorCodeEnum errorCode;
    public WalletsErrorResponse withErrorCode(WalletsErrorResponseErrorCodeEnum errorCode) {
        this.errorCode = errorCode;
        return this;
    }
    
    @JsonProperty("errorMessage")public String errorMessage;
    public WalletsErrorResponse withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }
    
}
