VERSION 0.7

sources:
    FROM ../..+base-build-image
    DO ../..+LOAD_SOURCES --LOCATION=libs/go-libs
    DO ../..+LOAD_SOURCES --LOCATION=sdks/go
    DO ../..+DOWNLOAD_DEPENDENCIES --LOCATION=components/orchestration
    DO ../..+LOAD_SOURCES --LOCATION=components/orchestration

    WORKDIR /src/components/orchestration

build-image:
    FROM ../..+base-final-image
    COPY (../..+build/orchestration --COMPONENT=orchestration) /bin/orchestration
    ENTRYPOINT ["/bin/orchestration"]

    DO ../..+SAVE_IMAGE --COMPONENT=orchestration

tests:
    FROM +sources
    WITH DOCKER --allow-privileged \
        --load postgres:15-alpine=+postgres
        DO ../..+GO_STD_TEST_COMMAND
    END
