<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Operations;


class InsertConfigResponse
{
    /**
     * Config created successfully.
     * 
     * @var ?\formance\stack\Models\Shared\ConfigResponse $configResponse
     */
	
    public ?\formance\stack\Models\Shared\ConfigResponse $configResponse = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Bad Request
     * 
     * @var ?string $insertConfig400TextPlainString
     */
	
    public ?string $insertConfig400TextPlainString = null;
    
	public function __construct()
	{
		$this->configResponse = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->insertConfig400TextPlainString = null;
	}
}
