---
on:
  workflow_call: {}

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 'stable'
    - run: sudo apt update
    - run: sudo apt install pre-commit git parallel -y
    - run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /bin
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /bin v1.51.2
    - run: pre-commit run --all-files -v
